import {
  Home,
  BookOpen,
  Users,
  PenLine,
  Archive,
  Trash2,
  Settings,
  Activity,
  FileText,
  Eye,
  BarChart3,
  ScrollText,
  Gauge,
  FolderOpen,
  PieChart,
  Download,
} from 'lucide-react';
import type { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  { key: 'sidebar.dashboard', icon: Home, href: '/dashboard', group: 'overview', requiresDb: true },
  { key: 'sidebar.posts', icon: BookOpen, href: '/posts', group: 'content' },
  { key: 'sidebar.faces', icon: Users, href: '/faces', group: 'content' },
  { key: 'sidebar.write', icon: PenLine, href: '/editor', group: 'content', requiresDb: true },
  { key: 'sidebar.articleManagement', icon: Archive, href: '/dashboard/articles', group: 'manage', requiresDb: true },
  { key: 'sidebar.trash', icon: Trash2, href: '/dashboard/articles?status=pending_deletion', group: 'manage', requiresDb: true },
  { key: 'sidebar.diary', icon: FileText, href: '/diary', group: 'personal', requiresDb: true },
  { key: 'sidebar.settings', icon: Settings, href: '/dashboard/settings', group: 'account', requiresDb: true },
  { key: 'sidebar.fileManager', icon: FolderOpen, href: '/dashboard/storage', group: 'storage', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.systemConfig', icon: Settings, href: '/dashboard/config', group: 'admin', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.configPreview', icon: Eye, href: '/dashboard/config/preview', group: 'admin', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.envVariables', icon: Activity, href: '/dashboard/env', group: 'admin', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.contentStats', icon: BarChart3, href: '/dashboard/stats', group: 'admin', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.analytics', icon: PieChart, href: '/dashboard/analytics', group: 'admin', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.webVitals', icon: Gauge, href: '/dashboard/web-vitals', group: 'admin', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.backup', icon: Download, href: '/dashboard/backup', group: 'admin', roles: ['sudo'], requiresDb: true },
  { key: 'sidebar.auditLogs', icon: ScrollText, href: '/dashboard/audit', group: 'admin', roles: ['sudo'], requiresDb: true },
];

export const groupKeys: Record<string, string> = {
  back: 'sidebar.returnDashboard',
  overview: 'dashboard.overview',
  content: 'dashboard.contentManagement',
  manage: 'dashboard.articles',
  personal: 'dashboard.personal',
  account: 'user.settings',
  admin: 'dashboard.adminConsole',
  storage: 'storage.title',
};
